Using a classification ML problem - discrete (rather than continuous)

If output consists of one or more CONTINUOUS variables, the task is regression

http://scikit-learn.org/stable/tutorial/basic/tutorial.html

http://scikit-learn.org/stable/auto_examples/svm/plot_rbf_parameters.html

https://www.quora.com/What-are-C-and-gamma-with-regards-to-a-support-vector-machine

In [13]:
from sklearn import datasets
from sklearn import svm

In [2]:
# Datasets are of type <class 'sklearn.utils.Bunch'>
iris = datasets.load_iris()
digits = datasets.load_digits()

# Digit classification

In [20]:
print type(digits)
print type(digits.data)
print type(digits.data[1,:])
print digits.data[1,:]

<class 'sklearn.utils.Bunch'>
<type 'numpy.ndarray'>
<type 'numpy.ndarray'>
[ 0.  0.  0. 12. 13.  5.  0.  0.  0.  0.  0. 11. 16.  9.  0.  0.  0.  0.
  3. 15. 16.  6.  0.  0.  0.  7. 15. 16. 16.  2.  0.  0.  0.  0.  1. 16.
 16.  3.  0.  0.  0.  0.  1. 16. 16.  6.  0.  0.  0.  0.  1. 16. 16.  6.
  0.  0.  0.  0.  0. 11. 16. 10.  0.  0.]


In [24]:
print 'Data description: Each row is an 8 X 8 image of a digit (0 - 9) to be classified'
print '\nDigit set shape: {}'.format(digits.data.shape)
print '\nDigit set data: {}'.format(digits.data)
print '\nDigit set target: {}'.format(digits.target)   

Data description: Each row is an 8 X 8 image of a digit (0 - 9) to be classified

Digit set shape: (1797, 64)

Digit set data: [[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]

Digit set target: [0 1 2 ... 8 9 8]


In [25]:
# Model used is support vector classification
# gamma = 
# C = trades off misclass of training examples against decision of training surface with a 
# low C making decision surface smooth while high C focuses on accuracy of prediction
clf = svm.SVC(gamma = 0.001, C = 100.)

In [26]:
# for this example, use all the images in the dataset except the last one
clf.fit(digits.data[:-1],digits.target[:-1])

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)