In [1]:
import numpy as np

np.random.seed(0) # seed for reproducibility


# np.array attributes

In [ ]:
# x1 = np.random.randint(10,size=6) # 1d array
x2 = np.random.randint(10,size=(3,4))  # 2d array
x3 = np.random.randint(10,size=(3,4,5))

In [10]:
print 'x1 = ',x1,'\n\n','x2 = \n',x2, '\n\n','x3 = \n',x3

x1 =  [5 0 3 3 7 9] 

x2 = 
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

x3 = 
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [32]:
# array atrrributes
print 'x3 attributes: \n', \
        '\n   x3.ndim: ',x3.ndim, \
        '\n   x3 shape: ',x3.shape, \
        '\n   x3 size: ', x3.size, \
        '\n   x3 dtype: ', x3.dtype, \
        '\n   x3 itemsize: ', x3.itemsize, \
        '\n   x3 nbytes: ', x3.nbytes, \
        '\n   x3 nbytes = itemsize * size: ', x3.size*x3.itemsize 
        

x3 attributes: 

   x3.ndim:  3 
   x3 shape:  (3, 4, 5) 
   x3 size:  60 
   x3 dtype:  int64 
   x3 itemsize:  8 
   x3 nbytes:  480 
   x3 nbytes = itemsize * size:  480


# Array indexing: accessing single elements

In [39]:
print 'x1: ',x1, \
'\n\n' 'x1[0]: ',x1[0], \
'\n' 'x1[4]: ', x1[4], \
'\n' 'x1[-1]: ', x1[-1], \
'\n' 'x1[-3]: ', x1[-3]

x1:  [5 0 3 3 7 9] 

x1[0]:  5 
x1[4]:  7 
x1[-1]:  9 
x1[-3]:  3


In [40]:
print 'x2: ',x2, \
'\n\n' 'x2[0,0]: ',x2[0,0], \
'\n' 'x2[2,0]: ', x2[2,0], \
'\n' 'x2[2,-1]: ', x2[2,-1]

x2:  [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

x2[0,0]:  3 
x2[2,0]:  1 
x2[2,-1]:  7


# Array slicing: accessing subarrays

Format: x[start:stop:step]

Defaults:

    start = 0 
    stop = size of dimension
    step = 1

In [41]:
# One dimensional subarrays

In [46]:
x = np.arange(10)
print x

[0 1 2 3 4 5 6 7 8 9]


In [69]:
import pprint
#help(pprint)

In [55]:
pp = pprint.PrettyPrinter(indent=4)
pp.pprint(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [68]:
print 'first 5 elements: ', x[:5], \
        '\nall elements after the 5th', x[5:], \
        '\n(4th element through 7th element): ', x[4:7], \
        '\nevery other element (evens): ',x[::2], \
        '\nevery other element starting at 1(odds): ',x[1::2]

first 5 elements:  [0 1 2 3 4] 
all elements after the 5th [5 6 7 8 9] 
(4th element through 7th element):  [4 5 6] 
every other element (evens):  [0 2 4 6 8] 
every other element starting at 1(odds):  [1 3 5 7 9]


In [61]:
x[:5]

array([0, 1, 2, 3, 4])

In [71]:
# negative step values 
#- in this case, the defaults for start and stop are swapped

In [74]:
print 'all elements, reversed: ', x[::-1], \
        '\nreversed every other from index 5: ', x[5::-2]

all elements, reversed:  [9 8 7 6 5 4 3 2 1 0] 
reversed every other from index 5:  [5 3 1]


#multidimensional subarrays

In [82]:
x2[0,0] = 12

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [76]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [93]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [89]:
print x2[:2,:3], '\n\n' #1st 2 rows, 1st 3 columns
x2[:3,::2] # all rows, every other column

[[12  5  2]
 [ 7  6  8]] 




array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [91]:
x2[::-1,::-1] # flips it so the [n,n] cell is the [0,0] cell & vice versa

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [92]:
x2[::2,::-1] # first row and last row backwards (skips)

array([[ 4,  2,  5, 12],
       [ 7,  7,  6,  1]])

In [94]:
x22 = np.random.randint(10,size=(10,10))

In [95]:
x22

array([[4, 3, 4, 4, 8, 4, 3, 7, 5, 5],
       [0, 1, 5, 9, 3, 0, 5, 0, 1, 2],
       [4, 2, 0, 3, 2, 0, 7, 5, 9, 0],
       [2, 7, 2, 9, 2, 3, 3, 2, 3, 4],
       [1, 2, 9, 1, 4, 6, 8, 2, 3, 0],
       [0, 6, 0, 6, 3, 3, 8, 8, 8, 2],
       [3, 2, 0, 8, 8, 3, 8, 2, 8, 4],
       [3, 0, 4, 3, 6, 9, 8, 0, 8, 5],
       [9, 0, 9, 6, 5, 3, 1, 8, 0, 4],
       [9, 6, 5, 7, 8, 8, 9, 2, 8, 6]])

In [96]:
x22[::2,::-1] #every other row backwards columns

array([[5, 5, 7, 3, 4, 8, 4, 4, 3, 4],
       [0, 9, 5, 7, 0, 2, 3, 0, 2, 4],
       [0, 3, 2, 8, 6, 4, 1, 9, 2, 1],
       [4, 8, 2, 8, 3, 8, 8, 0, 2, 3],
       [4, 0, 8, 1, 3, 5, 6, 9, 0, 9]])

In [100]:
x22[::-2,::2] # starting from bottom, every other row and every other col

array([[9, 5, 8, 9, 8],
       [3, 4, 6, 8, 8],
       [0, 0, 3, 8, 8],
       [2, 2, 2, 3, 3],
       [0, 5, 3, 5, 1]])

In [104]:
# accessing array rows and columns
print x2

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [105]:
print x2[:,0] # print the 0th element of each row (size = nrows)
print x2[0,:] # print the 0th row - all columns (size = ncol)

[12  7  1]
[12  5  2  4]


In [106]:
# array slices return views rather than copies of the array data
# different than Python list slicing - in lists, slices will be copies

In [108]:
# extract a 2X2 subarray
x2_sub = x2[:2,:2]
print x2_sub

[[12  5]
 [ 7  6]]


In [109]:
# modify subarray
x2_sub[0,0] = 99
print x2_sub

[[99  5]
 [ 7  6]]


In [110]:
# notice this changes x2 as well
print x2

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
